# Generated by Django 2.2.1 on 2019-06-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gusto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
