# Generated by Django 2.2.1 on 2019-06-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gusto', '0002_auto_20190623_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuSectionTitle',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_section_title',
            field=models.CharField(choices=[('BS', 'BREAKFAST & STARTERS'), ('MC', 'MAIN COURSE'), ('Di', 'DINNER'), ('De', 'DESSERTS')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
